janilla-com.api.cors.headers=Content-Type
janilla-com.api.cors.origin=https://localhost:8443
janilla-com.api.url=https://localhost:8444/api
janilla-com.backend.server.port=8444
janilla-com.database.file=~/janilla/sample-data/janilla-com.database
janilla-com.jwt.key=secretkey
janilla-com.live-demo=false
janilla-com.mail.host=smtp.example.com
janilla-com.mail.port=465
janilla-com.mail.username=foo.bar@example.com
janilla-com.mail.password=password
janilla-com.upload.directory=~/janilla/sample-data/janilla-com-upload
