janilla-com.api.url=https://localhost:8444/api
janilla-com.server.keystore.path=~/janilla/mykeystore
janilla-com.server.keystore.password=password
janilla-com.server.port=8443
janilla-com.jwt.key=secretkey
janilla-com.title=Janilla.com
