acme-dashboard.api.url=https://acmedashboard.janilla.local:8444/api

address-book.api.url=https://addressbook.janilla.local:8444/api

blank-template.api.url=https://blanktemplate.janilla.local:8444/api

conduit.api.url=https://conduit.janilla.local:8444/api

ecommerce-template.api.url=https://ecommercetemplate.janilla.local:8444/api

janilla-com.api.url=https://janilla.local:8444/api
janilla-com.authority=janilla.local:8443
janilla-com.download.directory=~/janilla/download
janilla-com.jwt.key=secretkey
janilla-com.server.keystore.password=password
janilla-com.server.keystore.path=~/janilla/mykeystore
janilla-com.server.port=8443
janilla-com.title=Janilla.com

petclinic.api.url=https://petclinic.janilla.local:8444/api

website-template.api.url=https://websitetemplate.janilla.local:8444/api
